[package]
name = "nest-egg-planner"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = { version = "0.4.2", features = ["websocket", "server"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
